%  Auto-generated by MATLAB on 21-Oct-2014 14:41:27

% Create figure
figure1 = figure;

% Create arrow
annotation(figure1,'arrow',[0.192857142857143 0.55],...
    [0.729952380952381 0.433333333333333]);

% Create ellipse
annotation(figure1,'ellipse',...
    [0.538499999999999 0.240476190476191 0.157928571428572 0.2452380952381]);

annotation(figure1,'textbox',...
    [0.3 0.348251748251748 0.0328486806677437 0.0517482517482517],...
    'String',{'y-x'},...
    'FontSize',16);

